version: "3"

services:
  pserve:
    build: .
    command: pserve /app/development-docker.ini --reload
    volumes:
      - .:/app
    ports:
      - 6543:6543
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  cvp_pgdata:
