version: "3"

services:
  pserve:
    build:
      context: .
      ssh:
        - default
    image: docker.ramp.eu/tds-pvt/pserve:latest
    command: /app/config/docker.ini --reload
    volumes:
      - .:/app
    ports:
      - 6543:6543
