version: "3"

services:
  pserve:
    build:
      context: .
      ssh:
        - default
    command: /app/config/docker.ini --reload
    volumes:
      - .:/app
    ports:
      - 6543:6543
    # env_file:
    #   - .env
