version: "3"

services:
  pserve:
    build:
      context: .
      ssh:
        - default
    image: docker.ramp.eu/tds-pvt/pserve:latest
    command: /app/config/docker.ini --reload
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./data:/app/data
      - ./better_factory:/app/better_factory
      - ./config:/app/config
      - ./openapi.yaml:/app/openapi.yaml
    ports:
      - 6543:6543
